[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "coma"
authors = [{name = "Francois Roewer-Despres", email = "coma.pypi@gmail.com"}]
dynamic = ["version", "description"]
